--- #YAML:1.0
name:               ex-monkeypatched
version:            0.03
abstract:           Experimental API for safe monkey-patching
author:
    - Aaron Crane <arc@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::Exception:  0
    Test::More:       0.88
requires:
    perl:       5.008
    Sub::Name:  0
resources:
    repository:  https://github.com/arc/p5-ex-monkeypatched
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
